[build]
  command = "npm ci --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.17.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200